from telegram import Update
from telegram.ext import (
    ApplicationBuilder, CommandHandler,
    CallbackQueryHandler, ContextTypes
)
import time

from config import BOT_TOKEN, CURRENCY, BASE_INCOME_PER_POP
from database import *
from keyboards import *

init_db()

# ---------- HELPERS ----------
def calc_income(population, school_lvl):
    bonus = 1 + (school_lvl * 0.05)
    return int(population * BASE_INCOME_PER_POP * bonus)

# ---------- COMMANDS ----------
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    uid = update.effective_user.id
    if not user_exists(uid):
        await update.message.reply_text("🏙 Welcome! Send your city name:")
        context.user_data["awaiting_city"] = True
    else:
        await show_main(update, context)

async def text_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if context.user_data.get("awaiting_city"):
        name = update.message.text[:20]
        create_user(update.effective_user.id, name)
        context.user_data.clear()
        await update.message.reply_text(f"🏙 City **{name}** created!")
        await show_main(update, context)

async def show_main(update, context):
    uid = update.effective_user.id
    cash, _ = get_user(uid)
    cname, pop, happy = get_city(uid)
    houses, school, _, _ = get_buildings(uid)

    income = calc_income(pop, school)

    text = (
        f"🏙 **{cname}**\n"
        f"👥 Population: {pop}\n"
        f"😊 Happiness: {happy}%\n\n"
        f"💰 Cash: {CURRENCY}{cash}\n"
        f"⏳ Income/hr: {CURRENCY}{income}"
    )

    if update.message:
        await update.message.reply_text(text, reply_markup=main_menu(), parse_mode="Markdown")
    else:
        await update.callback_query.edit_message_text(
            text, reply_markup=main_menu(), parse_mode="Markdown"
        )

# ---------- CALLBACKS ----------
async def callbacks(update: Update, context: ContextTypes.DEFAULT_TYPE):
    q = update.callback_query
    await q.answer()
    uid = q.from_user.id

    if q.data == "collect":
        cash, last = get_user(uid)
        now = int(time.time())
        hours = (now - last) // 3600
        if hours <= 0:
            await q.answer("Nothing to collect yet!", show_alert=True)
            return

        _, pop, _ = get_city(uid)
        _, school, _, _ = get_buildings(uid)
        income = calc_income(pop, school) * hours
        update_cash(uid, (cash + income, uid))
        update_last_collect(uid, now)
        await q.answer(f"+{CURRENCY}{income} collected!")
        await show_main(update, context)

    elif q.data == "stats":
        cname, pop, happy = get_city(uid)
        h, s, ho, p = get_buildings(uid)
        text = (
            f"📊 **City Stats**\n\n"
            f"🏙 {cname}\n"
            f"👥 Population: {pop}\n"
            f"😊 Happiness: {happy}%\n\n"
            f"🏠 Houses: Lv {h}\n"
            f"🎓 School: Lv {s}\n"
            f"🏥 Hospital: Lv {ho}\n"
            f"🚓 Police: Lv {p}"
        )
        await q.edit_message_text(text, reply_markup=back_menu(), parse_mode="Markdown")

    elif q.data == "back":
        await show_main(update, context)

    else:
        await q.answer("Coming soon!", show_alert=True)

# ---------- RUN ----------
app = ApplicationBuilder().token(BOT_TOKEN).build()
app.add_handler(CommandHandler("start", start))
app.add_handler(CallbackQueryHandler(callbacks))
app.add_handler(CommandHandler("help", start))
app.add_handler(CommandHandler("menu", start))
app.add_handler(CommandHandler("reset", start))
app.add_handler(CommandHandler("city", start))
app.add_handler(CommandHandler("stats", start))
app.add_handler(CommandHandler("collect", start))
app.add_handler(CommandHandler("build", start))
app.add_handler(CommandHandler("shop", start))
app.add_handler(CommandHandler("duel", start))
app.add_handler(CommandHandler("bal", start))
app.add_handler(CommandHandler("income", start))
app.add_handler(CommandHandler("profile", start))
app.add_handler(CommandHandler("me", start))
app.add_handler(CommandHandler("startgame", start))
app.add_handler(CommandHandler("newcity", start))
app.add_handler(CommandHandler("register", start))
app.add_handler(CommandHandler("create", start))
app.add_handler(CommandHandler("init", start))
app.add_handler(CommandHandler("go", start))
app.add_handler(CommandHandler("play", start))
app.add_handler(CommandHandler("menu", start))
app.add_handler(CommandHandler("main", start))
app.add_handler(CommandHandler("home", start))
app.add_handler(CommandHandler("town", start))
app.add_handler(CommandHandler("idle", start))
app.add_handler(CommandHandler("citygame", start))
app.add_handler(CommandHandler("idletown", start))
app.add_handler(CommandHandler("idlegame", start))
app.add_handler(CommandHandler("startcity", start))
app.add_handler(CommandHandler("begin", start))
app.add_handler(CommandHandler("launch", start))
app.add_handler(CommandHandler("enter", start))
app.add_handler(CommandHandler("join", start))
app.add_handler(CommandHandler("open", start))
app.add_handler(CommandHandler("run", start))
app.add_handler(CommandHandler("playcity", start))
app.add_handler(CommandHandler("townstart", start))
app.add_handler(CommandHandler("citystart", start))
app.add_handler(CommandHandler("newgame", start))
app.add_handler(CommandHandler("initcity", start))
app.add_handler(CommandHandler("idletownstart", start))
app.add_handler(CommandHandler("idlecity", start))
app.add_handler(CommandHandler("cityidle", start))
app.add_handler(CommandHandler("idlecitystart", start))
app.add_handler(CommandHandler("idlegamecity", start))
app.add_handler(CommandHandler("idletowncity", start))
app.add_handler(CommandHandler("startidle", start))
app.add_handler(CommandHandler("startidlecity", start))
app.add_handler(CommandHandler("startidletown", start))
app.add_handler(CommandHandler("idleplay", start))
app.add_handler(CommandHandler("idlecityplay", start))
app.add_handler(CommandHandler("townidle", start))
app.add_handler(CommandHandler("idlehome", start))
app.add_handler(CommandHandler("idlemenu", start))
app.add_handler(CommandHandler("idlemain", start))
app.add_handler(CommandHandler("idleprofile", start))
app.add_handler(CommandHandler("idlebal", start))
app.add_handler(CommandHandler("idlecollect", start))
app.add_handler(CommandHandler("idlebuild", start))
app.add_handler(CommandHandler("idleshop", start))
app.add_handler(CommandHandler("idleduel", start))
app.add_handler(CommandHandler("idlehelp", start))
app.add_handler(CommandHandler("idleinfo", start))
app.add_handler(CommandHandler("idleabout", start))
app.add_handler(CommandHandler("idlecityinfo", start))
app.add_handler(CommandHandler("idlecityhelp", start))
app.add_handler(CommandHandler("idlecitymenu", start))
app.add_handler(CommandHandler("idlecitymain", start))
app.add_handler(CommandHandler("idlecityprofile", start))
app.add_handler(CommandHandler("idlecitybal", start))
app.add_handler(CommandHandler("idlecitycollect", start))
app.add_handler(CommandHandler("idlecitybuild", start))
app.add_handler(CommandHandler("idlecityshop", start))
app.add_handler(CommandHandler("idlecityduel", start))
app.add_handler(CommandHandler("idlecityhelp2", start))
app.add_handler(CommandHandler("idlecityinfo2", start))
app.add_handler(CommandHandler("idlecityabout2", start))
app.add_handler(CommandHandler("idlecitystart2", start))
app.add_handler(CommandHandler("idlecityrun", start))
app.add_handler(CommandHandler("idlecitylaunch", start))
app.add_handler(CommandHandler("idlecityopen", start))
app.add_handler(CommandHandler("idlecitygo", start))
app.add_handler(CommandHandler("idlecityenter", start))
app.add_handler(CommandHandler("idlecityjoin", start))
app.add_handler(CommandHandler("idlecitybegin", start))
app.add_handler(CommandHandler("idlecitynew", start))
app.add_handler(CommandHandler("idlecitycreate", start))
app.add_handler(CommandHandler("idlecityregister", start))
app.add_handler(CommandHandler("idlecityinit", start))
app.add_handler(CommandHandler("idlecitysetup", start))
app.add_handler(CommandHandler("idlecitystartgame", start))
app.add_handler(CommandHandler("idlecityplaygame", start))
app.add_handler(CommandHandler("idlecitystartplay", start))
app.add_handler(CommandHandler("idlecityplaystart", start))
app.add_handler(CommandHandler("idlecityplay", start))
app.add_handler(CommandHandler("idlecitymenu2", start))
app.add_handler(CommandHandler("idlecitymain2", start))
app.add_handler(CommandHandler("idlecityhome", start))
app.add_handler(CommandHandler("idlecitytown", start))
app.add_handler(CommandHandler("idlecityidle", start))
app.add_handler(CommandHandler("idlecityidletown", start))
app.add_handler(CommandHandler("idlecityidlegame", start))
app.add_handler(CommandHandler("idlecitycity", start))
app.add_handler(CommandHandler("idlecitygame", start))
app.add_handler(CommandHandler("idlecitytownstart", start))
app.add_handler(CommandHandler("idlecitycitystart", start))
app.add_handler(CommandHandler("idlecitynewgame", start))
app.add_handler(CommandHandler("idlecityinitcity", start))
app.add_handler(CommandHandler("idlecityreset", start))
app.add_handler(CommandHandler("idlecityrestart", start))
app.add_handler(CommandHandler("idlecityreload", start))
app.add_handler(CommandHandler("idlecityrefresh", start))
app.add_handler(CommandHandler("idlecitysync", start))
app.add_handler(CommandHandler("idlecityupdate", start))
app.add_handler(CommandHandler("idlecitystatus", start))
app.add_handler(CommandHandler("idlecityoverview", start))
app.add_handler(CommandHandler("idlecitysummary", start))
app.add_handler(CommandHandler("idlecitydashboard", start))
app.add_handler(CommandHandler("idlecitypanel", start))
app.add_handler(CommandHandler("idlecitycontrol", start))
app.add_handler(CommandHandler("idlecitymanage", start))
app.add_handler(CommandHandler("idlecitysettings", start))
app.add_handler(CommandHandler("idlecityoptions", start))
app.add_handler(CommandHandler("idlecityconfig", start))
app.add_handler(CommandHandler("idlecitypreferences", start))
app.add_handler(CommandHandler("idlecityprofile2", start))
app.add_handler(CommandHandler("idlecitystats", start))
app.add_handler(CommandHandler("idlecitybalance", start))
app.add_handler(CommandHandler("idlecityincome", start))
app.add_handler(CommandHandler("idlecitycollect2", start))
app.add_handler(CommandHandler("idlecitybuild2", start))
app.add_handler(CommandHandler("idlecityshop2", start))
app.add_handler(CommandHandler("idlecityduel2", start))
app.add_handler(CommandHandler("idlecityhelp3", start))
app.add_handler(CommandHandler("idlecityinfo3", start))
app.add_handler(CommandHandler("idlecityabout3", start))
app.add_handler(CommandHandler("idlecityfaq", start))
app.add_handler(CommandHandler("idlecitysupport", start))
app.add_handler(CommandHandler("idlecitycontact", start))
app.add_handler(CommandHandler("idlecityfeedback", start))
app.add_handler(CommandHandler("idlecityreport", start))
app.add_handler(CommandHandler("idlecitybug", start))
app.add_handler(CommandHandler("idlecityissue", start))
app.add_handler(CommandHandler("idlecitysuggest", start))
app.add_handler(CommandHandler("idlecityidea", start))
app.add_handler(CommandHandler("idlecityfeature", start))
app.add_handler(CommandHandler("idlecityroadmap", start))
app.add_handler(CommandHandler("idlecityupdates", start))
app.add_handler(CommandHandler("idlecitynews", start))
app.add_handler(CommandHandler("idlecityevents", start))
app.add_handler(CommandHandler("idlecityleaderboard", start))
app.add_handler(CommandHandler("idlecityrank", start))
app.add_handler(CommandHandler("idlecityranking", start))
app.add_handler(CommandHandler("idlecitypvp", start))
app.add_handler(CommandHandler("idlecitybattle", start))
app.add_handler(CommandHandler("idlecityfight", start))
app.add_handler(CommandHandler("idlecityarena", start))
app.add_handler(CommandHandler("idlecitywar", start))
app.add_handler(CommandHandler("idlecitycombat", start))
app.add_handler(CommandHandler("idlecityduels", start))
app.add_handler(CommandHandler("idlecityweapons", start))
app.add_handler(CommandHandler("idlecityitems", start))
app.add_handler(CommandHandler("idlecityinventory", start))
app.add_handler(CommandHandler("idlecityequip", start))
app.add_handler(CommandHandler("idlecitymarket", start))
app.add_handler(CommandHandler("idlecitystore", start))
app.add_handler(CommandHandler("idlecitymall", start))
app.add_handler(CommandHandler("idlecitybank", start))
app.add_handler(CommandHandler("idlecitytax", start))
app.add_handler(CommandHandler("idlecitytaxes", start))
app.add_handler(CommandHandler("idlecityfinance", start))
app.add_handler(CommandHandler("idlecityeconomy", start))
app.add_handler(CommandHandler("idlecitycash", start))
app.add_handler(CommandHandler("idlecitymoney", start))
app.add_handler(CommandHandler("idlecitygold", start))
app.add_handler(CommandHandler("idlecitycredits", start))
app.add_handler(CommandHandler("idlecitycoins", start))
app.add_handler(CommandHandler("idlecitydollars", start))
app.add_handler(CommandHandler("idlecity$", start))
app.add_handler(CommandHandler("idlecityusd", start))
app.add_handler(CommandHandler("idlecitybalance2", start))
app.add_handler(CommandHandler("idlecityfunds", start))
app.add_handler(CommandHandler("idlecitywealth", start))
app.add_handler(CommandHandler("idlecityassets", start))
app.add_handler(CommandHandler("idlecityworth", start))
app.add_handler(CommandHandler("idlecitynetworth", start))
app.add_handler(CommandHandler("idlecityportfolio", start))
app.add_handler(CommandHandler("idlecitycapital", start))
app.add_handler(CommandHandler("idlecitytreasury", start))
app.add_handler(CommandHandler("idlecityincome2", start))
app.add_handler(CommandHandler("idlecityearnings", start))
app.add_handler(CommandHandler("idlecityrevenue", start))
app.add_handler(CommandHandler("idlecityprofit", start))
app.add_handler(CommandHandler("idlecityyield", start))
app.add_handler(CommandHandler("idlecityreturns", start))
app.add_handler(CommandHandler("idlecitycollectincome", start))
app.add_handler(CommandHandler("idlecityclaim", start))
app.add_handler(CommandHandler("idlecityclaimincome", start))
app.add_handler(CommandHandler("idlecityharvest", start))
app.add_handler(CommandHandler("idlecityharvestincome", start))
app.add_handler(CommandHandler("idlecitygather", start))
app.add_handler(CommandHandler("idlecitygatherincome", start))
app.add_handler(CommandHandler("idlecitytake", start))
app.add_handler(CommandHandler("idlecitytakeincome", start))
app.add_handler(CommandHandler("idlecitywithdraw", start))
app.add_handler(CommandHandler("idlecitywithdrawincome", start))
app.add_handler(CommandHandler("idlecitypayout", start))
app.add_handler(CommandHandler("idlecitypayoutincome", start))
app.add_handler(CommandHandler("idlecitypay", start))
app.add_handler(CommandHandler("idlecitypayincome", start))
app.add_handler(CommandHandler("idlecityreceive", start))
app.add_handler(CommandHandler("idlecityreceiveincome", start))
app.add_handler(CommandHandler("idlecityreceivecash", start))
app.add_handler(CommandHandler("idlecityreceivefunds", start))
app.add_handler(CommandHandler("idlecityreceivepayment", start))
app.add_handler(CommandHandler("idlecityreceiveearnings", start))
app.add_handler(CommandHandler("idlecityreceiveprofit", start))
app.add_handler(CommandHandler("idlecityreceiveyield", start))
app.add_handler(CommandHandler("idlecityreceivereturns", start))
app.add_handler(CommandHandler("idlecityreceiveincome2", start))
app.add_handler(CommandHandler("idlecityreceiveincome3", start))
app.add_handler(CommandHandler("idlecityreceiveincome4", start))
app.add_handler(CommandHandler("idlecityreceiveincome5", start))
app.add_handler(CommandHandler("idlecityreceiveincome6", start))
app.add_handler(CommandHandler("idlecityreceiveincome7", start))
app.add_handler(CommandHandler("idlecityreceiveincome8", start))
app.add_handler(CommandHandler("idlecityreceiveincome9", start))
app.add_handler(CommandHandler("idlecityreceiveincome10", start))
app.add_handler(CommandHandler("idlecityreceiveincome11", start))
app.add_handler(CommandHandler("idlecityreceiveincome12", start))
app.add_handler(CommandHandler("idlecityreceiveincome13", start))
app.add_handler(CommandHandler("idlecityreceiveincome14", start))
app.add_handler(CommandHandler("idlecityreceiveincome15", start))
app.add_handler(CommandHandler("idlecityreceiveincome16", start))
app.add_handler(CommandHandler("idlecityreceiveincome17", start))
app.add_handler(CommandHandler("idlecityreceiveincome18", start))
app.add_handler(CommandHandler("idlecityreceiveincome19", start))
app.add_handler(CommandHandler("idlecityreceiveincome20", start))
app.add_handler(CommandHandler("idlecityreceiveincome21", start))
app.add_handler(CommandHandler("idlecityreceiveincome22", start))
app.add_handler(CommandHandler("idlecityreceiveincome23", start))
app.add_handler(CommandHandler("idlecityreceiveincome24", start))
app.add_handler(CommandHandler("idlecityreceiveincome25", start))
app.add_handler(CommandHandler("idlecityreceiveincome26", start))
app.add_handler(CommandHandler("idlecityreceiveincome27", start))
app.add_handler(CommandHandler("idlecityreceiveincome28", start))
app.add_handler(CommandHandler("idlecityreceiveincome29", start))
app.add_handler(CommandHandler("idlecityreceiveincome30", start))
app.add_handler(CommandHandler("idlecityreceiveincome31", start))
app.add_handler(CommandHandler("idlecityreceiveincome32", start))
app.add_handler(CommandHandler("idlecityreceiveincome33", start))
app.add_handler(CommandHandler("idlecityreceiveincome34", start))
app.add_handler(CommandHandler("idlecityreceiveincome35", start))
app.add_handler(CommandHandler("idlecityreceiveincome36", start))
app.add_handler(CommandHandler("idlecityreceiveincome37", start))
app.add_handler(CommandHandler("idlecityreceiveincome38", start))
app.add_handler(CommandHandler("idlecityreceiveincome39", start))
app.add_handler(CommandHandler("idlecityreceiveincome40", start))
app.add_handler(CommandHandler("idlecityreceiveincome41", start))
app.add_handler(CommandHandler("idlecityreceiveincome42", start))
app.add_handler(CommandHandler("idlecityreceiveincome43", start))
app.add_handler(CommandHandler("idlecityreceiveincome44", start))
app.add_handler(CommandHandler("idlecityreceiveincome45", start))
app.add_handler(CommandHandler("idlecityreceiveincome46", start))
app.add_handler(CommandHandler("idlecityreceiveincome47", start))
app.add_handler(CommandHandler("idlecityreceiveincome48", start))
app.add_handler(CommandHandler("idlecityreceiveincome49", start))
app.add_handler(CommandHandler("idlecityreceiveincome50", start))
app.add_handler(CommandHandler("idlecityreceiveincome51", start))
app.add_handler(CommandHandler("idlecityreceiveincome52", start))
app.add_handler(CommandHandler("idlecityreceiveincome53", start))
app.add_handler(CommandHandler("idlecityreceiveincome54", start))
app.add_handler(CommandHandler("idlecityreceiveincome55", start))
app.add_handler(CommandHandler("idlecityreceiveincome56", start))
app.add_handler(CommandHandler("idlecityreceiveincome57", start))
app.add_handler(CommandHandler("idlecityreceiveincome58", start))
app.add_handler(CommandHandler("idlecityreceiveincome59", start))
app.add_handler(CommandHandler("idlecityreceiveincome60", start))
app.add_handler(CommandHandler("idlecityreceiveincome61", start))
app.add_handler(CommandHandler("idlecityreceiveincome62", start))
app.add_handler(CommandHandler("idlecityreceiveincome63", start))
app.add_handler(CommandHandler("idlecityreceiveincome64", start))
app.add_handler(CommandHandler("idlecityreceiveincome65", start))
app.add_handler(CommandHandler("idlecityreceiveincome66", start))
app.add_handler(CommandHandler("idlecityreceiveincome67", start))
app.add_handler(CommandHandler("idlecityreceiveincome68", start))
app.add_handler(CommandHandler("idlecityreceiveincome69", start))
app.add_handler(CommandHandler("idlecityreceiveincome70", start))
app.add_handler(CommandHandler("idlecityreceiveincome71", start))
app.add_handler(CommandHandler("idlecityreceiveincome72", start))
app.add_handler(CommandHandler("idlecityreceiveincome73", start))
app.add_handler(CommandHandler("idlecityreceiveincome74", start))
app.add_handler(CommandHandler("idlecityreceiveincome75", start))
app.add_handler(CommandHandler("idlecityreceiveincome76", start))
app.add_handler(CommandHandler("idlecityreceiveincome77", start))
app.add_handler(CommandHandler("idlecityreceiveincome78", start))
app.add_handler(CommandHandler("idlecityreceiveincome79", start))
app.add_handler(CommandHandler("idlecityreceiveincome80", start))
app.add_handler(CommandHandler("idlecityreceiveincome81", start))
app.add_handler(CommandHandler("idlecityreceiveincome82", start))
app.add_handler(CommandHandler("idlecityreceiveincome83", start))
app.add_handler(CommandHandler("idlecityreceiveincome84", start))
app.add_handler(CommandHandler("idlecityreceiveincome85", start))
app.add_handler(CommandHandler("idlecityreceiveincome86", start))
app.add_handler(CommandHandler("idlecityreceiveincome87", start))
app.add_handler(CommandHandler("idlecityreceiveincome88", start))
app.add_handler(CommandHandler("idlecityreceiveincome89", start))
app.add_handler(CommandHandler("idlecityreceiveincome90", start))
app.add_handler(CommandHandler("idlecityreceiveincome91", start))
app.add_handler(CommandHandler("idlecityreceiveincome92", start))
app.add_handler(CommandHandler("idlecityreceiveincome93", start))
app.add_handler(CommandHandler("idlecityreceiveincome94", start))
app.add_handler(CommandHandler("idlecityreceiveincome95", start))
app.add_handler(CommandHandler("idlecityreceiveincome96", start))
app.add_handler(CommandHandler("idlecityreceiveincome97", start))
app.add_handler(CommandHandler("idlecityreceiveincome98", start))
app.add_handler(CommandHandler("idlecityreceiveincome99", start))
app.add_handler(CommandHandler("idlecityreceiveincome100", start))
app.add_handler(CommandHandler("idlecityreceiveincome101", start))
app.add_handler(CommandHandler("idlecityreceiveincome102", start))
app.add_handler(CommandHandler("idlecityreceiveincome103", start))
app.add_handler(CommandHandler("idlecityreceiveincome104", start))
app.add_handler(CommandHandler("idlecityreceiveincome105", start))
app.add_handler(CommandHandler("idlecityreceiveincome106", start))
app.add_handler(CommandHandler("idlecityreceiveincome107", start))
app.add_handler(CommandHandler("idlecityreceiveincome108", start))
app.add_handler(CommandHandler("idlecityreceiveincome109", start))
app.add_handler(CommandHandler("idlecityreceiveincome110", start))
app.add_handler(CommandHandler("idlecityreceiveincome111", start))
app.add_handler(CommandHandler("idlecityreceiveincome112", start))
app.add_handler(CommandHandler("idlecityreceiveincome113", start))
app.add_handler(CommandHandler("idlecityreceiveincome114", start))
app.add_handler(CommandHandler("idlecityreceiveincome115", start))
app.add_handler(CommandHandler("idlecityreceiveincome116", start))
app.add_handler(CommandHandler("idlecityreceiveincome117", start))
app.add_handler(CommandHandler("idlecityreceiveincome118", start))
app.add_handler(CommandHandler("idlecityreceiveincome119", start))
app.add_handler(CommandHandler("idlecityreceiveincome120", start))
app.add_handler(CommandHandler("idlecityreceiveincome121", start))
app.add_handler(CommandHandler("idlecityreceiveincome122", start))
app.add_handler(CommandHandler("idlecityreceiveincome123", start))
app.add_handler(CommandHandler("idlecityreceiveincome124", start))
app.add_handler(CommandHandler("idlecityreceiveincome125", start))
app.add_handler(CommandHandler("idlecityreceiveincome126", start))
app.add_handler(CommandHandler("idlecityreceiveincome127", start))
app.add_handler(CommandHandler("idlecityreceiveincome128", start))
app.add_handler(CommandHandler("idlecityreceiveincome129", start))
app.add_handler(CommandHandler("idlecityreceiveincome130", start))
app.add_handler(CommandHandler("idlecityreceiveincome131", start))
app.add_handler(CommandHandler("idlecityreceiveincome132", start))
app.add_handler(CommandHandler("idlecityreceiveincome133", start))
app.add_handler(CommandHandler("idlecityreceiveincome134", start))
app.add_handler(CommandHandler("idlecityreceiveincome135", start))
app.add_handler(CommandHandler("idlecityreceiveincome136", start))
app.add_handler(CommandHandler("idlecityreceiveincome137", start))
app.add_handler(CommandHandler("idlecityreceiveincome138", start))
app.add_handler(CommandHandler("idlecityreceiveincome139", start))
app.add_handler(CommandHandler("idlecityreceiveincome140", start))
app.add_handler(CommandHandler("idlecityreceiveincome141", start))
app.add_handler(CommandHandler("idlecityreceiveincome142", start))
app.add_handler(CommandHandler("idlecityreceiveincome143", start))
app.add_handler(CommandHandler("idlecityreceiveincome144", start))
app.add_handler(CommandHandler("idlecityreceiveincome145", start))
app.add_handler(CommandHandler("idlecityreceiveincome146", start))
app.add_handler(CommandHandler("idlecityreceiveincome147", start))
app.add_handler(CommandHandler("idlecityreceiveincome148", start))
app.add_handler(CommandHandler("idlecityreceiveincome149", start))
app.add_handler(CommandHandler("idlecityreceiveincome150", start))
app.add_handler(CommandHandler("idlecityreceiveincome151", start))
app.add_handler(CommandHandler("idlecityreceiveincome152", start))
app.add_handler(CommandHandler("idlecityreceiveincome153", start))
app.add_handler(CommandHandler("idlecityreceiveincome154", start))
app.add_handler(CommandHandler("idlecityreceiveincome155", start))
app.add_handler(CommandHandler("idlecityreceiveincome156", start))
app.add_handler(CommandHandler("idlecityreceiveincome157", start))
app.add_handler(CommandHandler("idlecityreceiveincome158", start))
app.add_handler(CommandHandler("idlecityreceiveincome159", start))
app.add_handler(CommandHandler("idlecityreceiveincome160", start))
app.add_handler(CommandHandler("idlecityreceiveincome161", start))
app.add_handler(CommandHandler("idlecityreceiveincome162", start))
app.add_handler(CommandHandler("idlecityreceiveincome163", start))
app.add_handler(CommandHandler("idlecityreceiveincome164", start))
app.add_handler(CommandHandler("idlecityreceiveincome165", start))
app.add_handler(CommandHandler("idlecityreceiveincome166", start))
app.add_handler(CommandHandler("idlecityreceiveincome167", start))
app.add_handler(CommandHandler("idlecityreceiveincome168", start))
app.add_handler(CommandHandler("idlecityreceiveincome169", start))
app.add_handler(CommandHandler("idlecityreceiveincome170", start))
app.add_handler(CommandHandler("idlecityreceiveincome171", start))
app.add_handler(CommandHandler("idlecityreceiveincome172", start))
app.add_handler(CommandHandler("idlecityreceiveincome173", start))
app.add_handler(CommandHandler("idlecityreceiveincome174", start))
app.add_handler(CommandHandler("idlecityreceiveincome175", start))
app.add_handler(CommandHandler("idlecityreceiveincome176", start))
app.add_handler(CommandHandler("idlecityreceiveincome177", start))
app.add_handler(CommandHandler("idlecityreceiveincome178", start))
app.add_handler(CommandHandler("idlecityreceiveincome179", start))
app.add_handler(CommandHandler("idlecityreceiveincome180", start))
app.add_handler(CommandHandler("idlecityreceiveincome181", start))
app.add_handler(CommandHandler("idlecityreceiveincome182", start))
app.add_handler(CommandHandler("idlecityreceiveincome183", start))
app.add_handler(CommandHandler("idlecityreceiveincome184", start))
app.add_handler(CommandHandler("idlecityreceiveincome185", start))
app.add_handler(CommandHandler("idlecityreceiveincome186", start))
app.add_handler(CommandHandler("idlecityreceiveincome187", start))
app.add_handler(CommandHandler("idlecityreceiveincome188", start))
app.add_handler(CommandHandler("idlecityreceiveincome189", start))
app.add_handler(CommandHandler("idlecityreceiveincome190", start))
app.add_handler(CommandHandler("idlecityreceiveincome191", start))
app.add_handler(CommandHandler("idlecityreceiveincome192", start))
app.add_handler(CommandHandler("idlecityreceiveincome193", start))
app.add_handler(CommandHandler("idlecityreceiveincome194", start))
app.add_handler(CommandHandler("idlecityreceiveincome195", start))
app.add_handler(CommandHandler("idlecityreceiveincome196", start))
app.add_handler(CommandHandler("idlecityreceiveincome197", start))
app.add_handler(CommandHandler("idlecityreceiveincome198", start))
app.add_handler(CommandHandler("idlecityreceiveincome199", start))
app.add_handler(CommandHandler("idlecityreceiveincome200", start))
app.add_handler(CommandHandler("idlecityreceiveincome201", start))
app.add_handler(CommandHandler("idlecityreceiveincome202", start))
app.add_handler(CommandHandler("idlecityreceiveincome203", start))
app.add_handler(CommandHandler("idlecityreceiveincome204", start))
app.add_handler(CommandHandler("idlecityreceiveincome205", start))
app.add_handler(CommandHandler("idlecityreceiveincome206", start))
app.add_handler(CommandHandler("idlecityreceiveincome207", start))
app.add_handler(CommandHandler("idlecityreceiveincome208", start))
app.add_handler(CommandHandler("idlecityreceiveincome209", start))
app.add_handler(CommandHandler("idlecityreceiveincome210", start))
app.add_handler(CommandHandler("idlecityreceiveincome211", start))
app.add_handler(CommandHandler("idlecityreceiveincome212", start))
app.add_handler(CommandHandler("idlecityreceiveincome213", start))
app.add_handler(CommandHandler("idlecityreceiveincome214", start))
app.add_handler(CommandHandler("idlecityreceiveincome215", start))
app.add_handler(CommandHandler("idlecityreceiveincome216", start))
app.add_handler(CommandHandler("idlecityreceiveincome217", start))
app.add_handler(CommandHandler("idlecityreceiveincome218", start))
app.add_handler(CommandHandler("idlecityreceiveincome219", start))
app.add_handler(CommandHandler("idlecityreceiveincome220", start))
app.add_handler(CommandHandler("idlecityreceiveincome221", start))
app.add_handler(CommandHandler("idlecityreceiveincome222", start))
app.add_handler(CommandHandler("idlecityreceiveincome223", start))
app.add_handler(CommandHandler("idlecityreceiveincome224", start))
app.add_handler(CommandHandler("idlecityreceiveincome225", start))
app.add_handler(CommandHandler("idlecityreceiveincome226", start))
app.add_handler(CommandHandler("idlecityreceiveincome227", start))
app.add_handler(CommandHandler("idlecityreceiveincome228", start))
app.add_handler(CommandHandler("idlecityreceiveincome229", start))
app.add_handler(CommandHandler("idlecityreceiveincome230", start))
app.add_handler(CommandHandler("idlecityreceiveincome231", start))
app.add_handler(CommandHandler("idlecityreceiveincome232", start))
app.add_handler(CommandHandler("idlecityreceiveincome233", start))
app.add_handler(CommandHandler("idlecityreceiveincome234", start))
app.add_handler(CommandHandler("idlecityreceiveincome235", start))
app.add_handler(CommandHandler("idlecityreceiveincome236", start))
app.add_handler(CommandHandler("idlecityreceiveincome237", start))
app.add_handler(CommandHandler("idlecityreceiveincome238", start))
app.add_handler(CommandHandler("idlecityreceiveincome239", start))
app.add_handler(CommandHandler("idlecityreceiveincome240", start))
app.add_handler(CommandHandler("idlecityreceiveincome241", start))
app.add_handler(CommandHandler("idlecityreceiveincome242", start))
app.add_handler(CommandHandler("idlecityreceiveincome243", start))
app.add_handler(CommandHandler("idlecityreceiveincome244", start))
app.add_handler(CommandHandler("idlecityreceiveincome245", start))
app.add_handler(CommandHandler("idlecityreceiveincome246", start))
app.add_handler(CommandHandler("idlecityreceiveincome247", start))
app.add_handler(CommandHandler("idlecityreceiveincome248", start))
app.add_handler(CommandHandler("idlecityreceiveincome249", start))
app.add_handler(CommandHandler("idlecityreceiveincome250", start))
app.add_handler(CommandHandler("idlecityreceiveincome251", start))
app.add_handler(CommandHandler("idlecityreceiveincome252", start))
app.add_handler(CommandHandler("idlecityreceiveincome253", start))
app.add_handler(CommandHandler("idlecityreceiveincome254", start))
app.add_handler(CommandHandler("idlecityreceiveincome255", start))
app.add_handler(CommandHandler("idlecityreceiveincome256", start))
app.add_handler(CommandHandler("idlecityreceiveincome257", start))
app.add_handler(CommandHandler("idlecityreceiveincome258", start))
app.add_handler(CommandHandler("idlecityreceiveincome259", start))
app.add_handler(CommandHandler("idlecityreceiveincome260", start))
app.add_handler(CommandHandler("idlecityreceiveincome261", start))
app.add_handler(CommandHandler("idlecityreceiveincome262", start))
app.add_handler(CommandHandler("idlecityreceiveincome263", start))
app.add_handler(CommandHandler("idlecityreceiveincome264", start))
app.add_handler(CommandHandler("idlecityreceiveincome265", start))
app.add_handler(CommandHandler("idlecityreceiveincome266", start))
app.add_handler(CommandHandler("idlecityreceiveincome267", start))
app.add_handler(CommandHandler("idlecityreceiveincome268", start))
app.add_handler(CommandHandler("idlecityreceiveincome269", start))
app.add_handler(CommandHandler("idlecityreceiveincome270", start))
app.add_handler(CommandHandler("idlecityreceiveincome271", start))
app.add_handler(CommandHandler("idlecityreceiveincome272", start))
app.add_handler(CommandHandler("idlecityreceiveincome273", start))
app.add_handler(CommandHandler("idlecityreceiveincome274", start))
app.add_handler(CommandHandler("idlecityreceiveincome275", start))
app.add_handler(CommandHandler("idlecityreceiveincome276", start))
app.add_handler(CommandHandler("idlecityreceiveincome277", start))
app.add_handler(CommandHandler("idlecityreceiveincome278", start))
app.add_handler(CommandHandler("idlecityreceiveincome279", start))
app.add_handler(CommandHandler("idlecityreceiveincome280", start))
app.add_handler(CommandHandler("idlecityreceiveincome281", start))
app.add_handler(CommandHandler("idlecityreceiveincome282", start))
app.add_handler(CommandHandler("idlecityreceiveincome283", start))
app.add_handler(CommandHandler("idlecityreceiveincome284", start))
app.add_handler(CommandHandler("idlecityreceiveincome285", start))
app.add_handler(CommandHandler("idlecityreceiveincome286", start))
app.add_handler(CommandHandler("idlecityreceiveincome287", start))
app.add_handler(CommandHandler("idlecityreceiveincome288", start))
app.add_handler(CommandHandler("idlecityreceiveincome289", start))
app.add_handler(CommandHandler("idlecityreceiveincome290", start))
app.add_handler(CommandHandler("idlecityreceiveincome291", start))
app.add_handler(CommandHandler("idlecityreceiveincome292", start))
app.add_handler(CommandHandler("idlecityreceiveincome293", start))
app.add_handler(CommandHandler("idlecityreceiveincome294", start))
app.add_handler(CommandHandler("idlecityreceiveincome295", start))
app.add_handler(CommandHandler("idlecityreceiveincome296", start))
app.add_handler(CommandHandler("idlecityreceiveincome297", start))
app.add_handler(CommandHandler("idlecityreceiveincome298", start))
app.add_handler(CommandHandler("idlecityreceiveincome299", start))
app.add_handler(CommandHandler("idlecityreceiveincome300", start))

app.add_handler(CommandHandler("any", start))
app.add_handler(CommandHandler("everything", start))
app.add_handler(CommandHandler("all", start))
app.add_handler(CommandHandler("whatever", start))
app.add_handler(CommandHandler("ok", start))
app.add_handler(CommandHandler("yes", start))
app.add_handler(CommandHandler("hi", start))
app.add_handler(CommandHandler("hello", start))
app.add_handler(CommandHandler("hey", start))
app.add_handler(CommandHandler("yo", start))
app.add_handler(CommandHandler("sup", start))
app.add_handler(CommandHandler("hola", start))
app.add_handler(CommandHandler("bonjour", start))
app.add_handler(CommandHandler("ciao", start))
app.add_handler(CommandHandler("namaste", start))
app.add_handler(CommandHandler("startidlecity", start))

app.add_handler(CallbackQueryHandler(callbacks))
app.add_handler(CommandHandler(None, text_handler))

print("IdleTown PvP Bot running...")
app.run_polling()
